import {ENEMIES,LEVELS} from './config.js';
const descriptions={
  bow:{role:'Archer',mechanic:'Winds up a single arrow aimed at you.',counter:'Face the arrow and parry it back, block, or step out of its path.'},
  pistol:{role:'Gunner',mechanic:'Fires fast bullets. Every third volley is red and cannot be parried.',counter:'Parry ordinary shots. Block or dodge red shots; watch the wind-up before rushing in.'},
  homing:{role:'Tracking shots',mechanic:'Launches slow projectiles that curve toward you.',counter:'Parry to send a faster homing shot back at enemies. Dodging works best when you also change direction.'},
  shotgun:{role:'Spread shots',mechanic:'Fires a fan of projectiles that is dangerous at close range.',counter:'Keep enough space to move between shots, or face the spread and time a parry.'},
  mortar:{role:'Area attack',mechanic:'Lobs an arcing shell toward where your movement is taking you. A marked circle shows its blast area.',counter:'Change direction after the landing marker appears, dash out, or block toward the blast. The explosion cannot be parried.'},
  brawler:{role:'Melee',mechanic:'Closes the distance and winds up a short, wide melee swing.',counter:'Parry the strike to stun it for one second. Attack during the stun, or step out of the marked swing.'},
  lancer:{role:'Long-range melee',mechanic:'Uses a long-reaching thrust with a narrower attack arc.',counter:'Sidestep the thrust or parry it to stun the Lancer for one second. Its reach is longer than it looks.'},
  railgun:{role:'Beam attack',mechanic:'After a short red laser warning, fires a fixed beam that stays dangerous along its entire line for one second. It aims at your current position.',counter:'Move off the line or dash across it. The beam cannot be parried, but can be blocked. Stone cover stops the beam.'},
  boss:{role:'Level 1 boss',mechanic:'The Brass Warden repositions and mixes ordinary and red volleys. At low health it adds surrounding shots and mortar shells. Its close shockwave has a red wind-up and deals 20 damage.',counter:'React to each tell: parry ordinary shots, block or dodge red attacks, and back away from the close shockwave. Nearby AoE can trigger through cover.'},
  miner:{role:'Proximity traps',mechanic:'Approaches, drops a mine, flees to a safe distance, then holds until its five-second cooldown ends. The timer runs during retreat. It can place unlimited mines. Mines take one second to arm, then give a 0.4-second warning when triggered.',counter:'Avoid armed mines, or face and parry the mine itself during its warning fuse to send it flying. A returned mine explodes on an enemy or wall and damages enemies nearby.'},
  ricochet:{role:'Bouncing shots',mechanic:'Fires projectiles that bounce off walls and stone cover twice. The third impact removes them.',counter:'Watch the rebound path as well as the first shot. Parry, block or dodge; simple cover can send a shot back around you.'},
  suicide:{role:'Dash-only explosion',mechanic:'Charges toward you and starts a short, random red fuse. It is immune to attacks and only dies when it detonates. Hiding within its blast radius can trigger the fuse through cover.',counter:'Time your dash invulnerability for the explosion. Ordinary running, blocking and parrying do not stop its DASH ONLY blast.'},
  cluster:{role:'Scattering grenade',mechanic:'Lobs a heavy grenade. It lands, rests briefly, then splits into five projectiles that scatter outward.',counter:'Leave the grenade before it splits and watch the five outgoing paths. The scattered shots can be parried or blocked.'},
  magnet:{role:'Projectile attraction',mechanic:'Fires a fast tracking dart that deals no damage. If it attaches, all hostile projectiles bend toward you for five seconds. Blocking does not stop attachment.',counter:'Parry or dodge the dart. While marked, stay mobile and expect ricochets and other shots to change direction. Your parried projectiles remain friendly.'},
  sine:{role:'Wave shots',mechanic:'Fires projectiles that undulate along a sine wave instead of traveling in a straight line.',counter:'Watch the curves and sidestep into their gaps, or parry the incoming shot. Judge its current path rather than only its original aim.'},
  riot:{role:'Ally protector',mechanic:'Moves quickly to stand between you and nearby allies, prioritizing ranged enemies. Its front shield provides mobile cover, but turns slowly. Its melee strike deals little damage but pushes you far away.',counter:'Dash around its shield and strike before it turns to face you. Parry its melee strike to stun it, then attack the exposed unit or the allies it was protecting.'},
  boomerang:{role:'Returning projectile',mechanic:'Throws one wide-arcing boomerang at a time. It turns back toward its owner and can hit you on both passes.',counter:'Dodge both the outgoing throw and the return. Its red projectile cannot be parried, but can be blocked while facing it.'},
  twinBomber:{role:'Level 2 twin boss',mechanic:'The Bomber stays mobile, plants ground mines and lobs cluster grenades. Each grenade lands, pauses, then scatters into five projectiles. Its mines take one second to arm and give a 0.4-second trigger warning.',counter:'Keep moving between the safe spaces, avoid mine trails or parry the mine during its warning fuse. Returned mines explode on enemy or wall contact. Fight it alongside its twin, The Ricochet; both must fall.'},
  twinRicochet:{role:'Level 2 twin boss',mechanic:'The Ricochet fires spreads that bounce twice before disappearing on their third impact, while The Bomber fills the arena with traps.',counter:'Track rebound paths while leaving the Bomber’s danger zones. Parry or dodge shots and avoid backing into corners. Both twins must be defeated.'},
};
export const ENEMY_GUIDE=LEVELS.flatMap((level,index)=>[...level.enemies,...level.bosses].map(id=>({id,name:ENEMIES[id].name,level:index+1,area:level.name,boss:!!ENEMIES[id].boss,...descriptions[id]})));
export function filterEnemies(query='',level=0){const term=query.trim().toLowerCase();return ENEMY_GUIDE.filter(enemy=>(!level||enemy.level===level)&&(!term||`${enemy.name} ${enemy.role} ${enemy.mechanic} ${enemy.counter}`.toLowerCase().includes(term)));}
