'use client';
import {KITS} from './run-content.js';
import {WEAPONS,UPGRADES} from './config.js';

export default function RunPanels({game:g,player:p,host,action}){
  if(g.phase==='draft'){
    const near=g.kits.find(k=>!k.claimedBy&&p&&Math.hypot(p.x-k.x,p.y-k.y)<=80),kit=near&&KITS.find(k=>k.id===near.id);
    return <div className="run-hint"><b>Starting kit draft · {g.players.filter(q=>q.kitId).length}/{g.players.length} chosen</b><p>{p?.kitId?'Your kit is locked. Wait for your party to pick.':'Walk to a weapon pickup. First to grab it gets it.'}</p>{kit&&!p.kitId&&<><strong>{kit.name} · {WEAPONS[kit.weapon].name}</strong><p>{kit.desc}</p><button onClick={()=>action('kit',{kit:kit.id})}>Grab kit · E</button></>}</div>;
  }
  if(g.phase==='route')return <section className="screen-modal centered route-modal"><span className="eyebrow">EXTRA STOPS · NEXT: ROOM {g.pendingRoom+1}</span><h2>Choose the route.</h2><p>{host?'Choose where the party goes next.':'Waiting for the host to choose the route.'}</p><div className="reward-grid">{g.routeOptions.map(choice=><button className="reward" key={choice} disabled={!host} onClick={()=>action('route',{choice})}><b>{choice==='shop'?'Vending room':choice==='altar'?'Sacrifice altar':'Continue to combat'}</b><p>{choice==='shop'?'Spend shared Scrap on limited stock.':choice==='altar'?'Trade 25% maximum health for a relic.':'Keep your Scrap and advance.'}</p></button>)}</div></section>;
  if(!['shop','altar'].includes(g.phase))return null;
  const open=g.phase==='shop'?p?.vendorOpen:p?.altarOpen;
  if(!open)return <div className="run-hint"><b>{g.phase==='shop'?'Vending room':'Sacrifice room'} · {g.scrap} shared Scrap</b><p>Walk to the {g.phase==='shop'?'vending machine':'altar'} and press E to interact. {host?'Use E at the right-hand exit to continue.':'The host chooses when the party leaves.'}</p></div>;
  return <section className="screen-modal centered vendor-modal" role="dialog" aria-label={g.phase==='shop'?'Vending machine':'Sacrifice altar'}><span className="eyebrow">{g.phase==='shop'?`${g.scrap} SHARED SCRAP · LIMITED STOCK`:'PERMANENT RUN SACRIFICE'}</span><h2>{g.phase==='shop'?'Spend it or save it.':'Power has a price.'}</h2><strong className="vendor-stats">HP {Math.ceil(p.hp)} / {p.maxHp} · SHIELD {100-(p.shieldDamage||0)} / 100</strong><p>{g.phase==='shop'?'Purchases affect you. Everyone uses the same Scrap and stock.':p.altarUsed===g.stopSerial?'Sacrifice accepted. Your health penalty lasts for the remainder of this run.':`Lose ${Math.ceil(p.maxHp*.25)} maximum HP (25%) for one relic. The penalty also applies to future health gains.`}</p><div className="reward-grid">{g.phase==='shop'?g.stock.map(item=><button className="reward" key={item.id} disabled={!item.left||g.scrap<item.cost||(UPGRADES.find(u=>u.id===item.id)?.kind&&p.upgrades.includes(item.id))} onClick={()=>action('buy',{item:item.id})}><div><b>{item.name}</b><small>{item.desc}</small><strong>{item.cost} Scrap · {item.left} left</strong></div></button>):g.altarOffers.map(id=>{const u=UPGRADES.find(u=>u.id===id);return <button className="reward" key={id} disabled={p.altarUsed===g.stopSerial||p.upgrades.includes(id)||p.maxHp<20} onClick={()=>action('sacrifice',{item:id})}><span>{u.icon}</span><div><b>{u.name}</b><small>{u.desc}</small></div></button>;})}</div><button className="secondary" onClick={()=>action('vendorClose')}>Back to arena · Esc</button></section>;
}
