'use client';
import {useEffect,useRef,useState} from 'react';
import {ENEMIES,LEVELS,UPGRADES} from './config.js';
import {CURSES} from './run-content.js';
import {Renderer} from './renderer.js';
import {filterEnemies} from './enemy-guide.js';
const portraits=new Map();
// Render the actual in-game sprite once, then reuse a static image. No animation
// loop, audio context or particle pools are created for encyclopedia portraits.
function portrait(kind){
  if(portraits.has(kind))return portraits.get(kind);
  const canvas=document.createElement('canvas');canvas.width=384;canvas.height=272;
  const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;c.translate(112,140);c.scale(2.4,2.4);
  const cfg=ENEMIES[kind],enemy={kind,x:0,y:0,angle:0,hp:cfg.hp,maxHp:cfg.hp,stun:0,tell:0,swing:0,guardLeft:0,recoil:0,minesLaid:0,mineTimer:cfg.rate,mineState:'approach'};
  Renderer.prototype.enemy.call({weapon:Renderer.prototype.weapon},c,enemy);
  const src=canvas.toDataURL('image/png');portraits.set(kind,src);return src;
}
// Cached local PNGs need no image optimizer or network request.
/* eslint-disable @next/next/no-img-element */
function EnemyPortrait({enemy}){const ref=useRef(null);useEffect(()=>{ref.current.src=portrait(enemy.id);},[enemy.id]);return <img ref={ref} className="enemy-portrait" width={384} height={272} alt={`${enemy.name} with its in-game equipment`}/>;}
export default function Settings({onClose,muted,onToggleSound,online,active,isHost,player,stage,room,onAdmin}){
  const [page,setPage]=useState('settings'),[query,setQuery]=useState(''),[level,setLevel]=useState(0),dialog=useRef(null);
  useEffect(()=>{dialog.current?.focus();},[page]);
  function trapFocus(event){if(event.key!=='Tab')return;const elements=[...dialog.current.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),[href]')];if(!elements.length)return;event.preventDefault();const current=elements.indexOf(document.activeElement),next=current<0?(event.shiftKey?elements.length-1:0):(current+(event.shiftKey?-1:1)+elements.length)%elements.length;elements[next].focus();}
  const enemies=filterEnemies(query,level);
  return <section className="screen-modal settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title" tabIndex={-1} ref={dialog} onKeyDown={trapFocus}>
    <header className="settings-header"><div><span className="eyebrow">{page==='enemies'?'SETTINGS / FIELD GUIDE':'PARRY GROVE'}</span><h2 id="settings-title">{page==='enemies'?'Enemy encyclopedia':'Settings'}</h2></div><button className="secondary settings-close" onClick={onClose}>Close · Esc</button></header>
    {page==='settings'?<div className="settings-home"><p>{online?'Your co-op run continues while Settings is open.':'You can browse safely; Settings pauses your solo run.'}</p><button className="settings-option" onClick={onToggleSound} aria-pressed={!muted}><span>Sound</span><b>{muted?'Off':'On'}</b></button><button className="settings-option encyclopedia-link" onClick={()=>setPage('enemies')}><span><strong>Enemy encyclopedia</strong><small>Meet every enemy and boss. Learn their attacks and how to respond.</small></span><b>Open ↗</b></button><AdminBar active={active} online={online} isHost={isHost} player={player} stage={stage} room={room} onAdmin={onAdmin}/></div>:<>
      <div className="guide-toolbar"><button className="text-button" onClick={()=>setPage('settings')}>← Back to Settings</button><label className="guide-search">Search enemies<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or mechanic…" type="search"/></label><div className="guide-filters" aria-label="Filter enemies by level">{[[0,'All enemies'],[1,'Level 1'],[2,'Level 2']].map(([id,label])=><button key={id} onClick={()=>setLevel(id)} aria-pressed={level===id}>{label}</button>)}</div></div>
      <p className="guide-rules">Cover stops direct shots. Nearby area attacks can trigger through cover. Red attacks can usually be blocked or dodged; <b>DASH ONLY</b> explosions require a timed dash.</p>
      <div className="guide-count" role="status">{enemies.length} {enemies.length===1?'entry':'entries'}</div>
      <div className="enemy-guide-grid">{enemies.map(enemy=><article className="enemy-guide-card" key={enemy.id}><div className="enemy-card-heading"><div className="enemy-portrait-frame"><EnemyPortrait enemy={enemy}/></div><div><span className="enemy-area">LEVEL {enemy.level} · {enemy.boss?'BOSS':enemy.area.toUpperCase()}</span><h3>{enemy.name}</h3><span className="enemy-role">{enemy.role}</span></div></div><div className="enemy-guide-copy"><h4>How it works</h4><p>{enemy.mechanic}</p><h4>How to respond</h4><p>{enemy.counter}</p></div></article>)}</div>
      {!enemies.length&&<div className="guide-empty"><h3>No enemies found.</h3><p>Try another name, mechanic or level.</p><button className="secondary" onClick={()=>{setQuery('');setLevel(0);}}>Reset filters</button></div>}
    </>}
  </section>;
}

function AdminBar({active,online,isHost,player,stage,room,onAdmin}){
  const [level,setLevel]=useState(stage+1),[targetRoom,setTargetRoom]=useState(room+1),[hp,setHp]=useState(String(Math.ceil(player?.hp||player?.maxHp||100))),[playerLevel,setPlayerLevel]=useState(String(player?.level||1)),[upgrade,setUpgrade]=useState(UPGRADES[0]?.id||''),[curse,setCurse]=useState(CURSES[0]?.id||''),[rarity,setRarity]=useState('common'),[removeUpgrade,setRemoveUpgrade]=useState(player?.upgrades?.[0]||''),[removeCurse,setRemoveCurse]=useState('0'),[working,setWorking]=useState(false),[notice,setNotice]=useState('');
  const enabled=active&&(!online||isHost)&&!working,ownedUpgrades=player?.upgrades||[],ownedCurses=player?.curses||[],selectedRemoveUpgrade=ownedUpgrades.includes(removeUpgrade)?removeUpgrade:ownedUpgrades[0]||'';
  async function apply(operation,values={}){setWorking(true);setNotice('');try{await onAdmin(operation,values);const messages={teleport:`Teleported to Level ${level}, Room ${targetRoom}.`,health:`HP set to ${Number(hp).toLocaleString()}.`,level:`Player level set to ${Number(playerLevel)}; XP progress reset.`,upgradeAdd:`Added ${UPGRADES.find(u=>u.id===upgrade)?.name||'upgrade'}.`,upgradeRemove:`Removed ${UPGRADES.find(u=>u.id===removeUpgrade)?.name||'upgrade'}.`,curseAdd:`Added ${CURSES.find(c=>c.id===curse)?.name||'curse'} (${rarity}).`,curseRemove:'Removed selected curse.'};setNotice(messages[operation]||'Admin action complete.');}catch(e){setNotice(e.message);}finally{setWorking(false);}}
  return <section className="admin-bar" aria-labelledby="admin-title"><h3 id="admin-title">Admin controls</h3><p>{!active?'Start a run to use these controls.':online&&!isHost?'Only the co-op host can use admin controls.':online?'Teleport moves the whole party. Other actions apply to you.':'Teleport anywhere while keeping your stats and upgrades.'}</p>
    <form className="admin-controls" onSubmit={e=>{e.preventDefault();if(enabled)apply('teleport',{level,room:targetRoom});}}><label>Level<select value={level} disabled={!enabled} onChange={e=>setLevel(Number(e.target.value))}>{LEVELS.map((l,i)=><option key={l.name} value={i+1}>{i+1} · {l.name}</option>)}</select></label><label>Room<select value={targetRoom} disabled={!enabled} onChange={e=>setTargetRoom(Number(e.target.value))}>{[1,2,3,4,5].map(r=><option key={r} value={r}>{r}{r===5?' · Boss':''}</option>)}</select></label><button className="secondary" disabled={!enabled} type="submit">Teleport</button></form>
    <form className="admin-controls" onSubmit={e=>{e.preventDefault();if(enabled)apply('health',{hp:hp.trim()?Number(hp):NaN});}}><label>Custom HP<input type="number" min="1" max="1000000" step="1" required value={hp} disabled={!enabled} onChange={e=>setHp(e.target.value)}/></label><button className="secondary" disabled={!enabled} type="submit">Set HP</button></form><small>HP above your maximum raises the maximum to match. Range: 1–1,000,000.</small>
    <form className="admin-controls" onSubmit={e=>{e.preventDefault();if(enabled)apply('level',{level:Number(playerLevel)});}}><label>Player level<input type="number" min="1" max="100" step="1" required value={playerLevel} disabled={!enabled} onChange={e=>setPlayerLevel(e.target.value)}/></label><button className="secondary" disabled={!enabled} type="submit">Set level</button></form><small>Sets your level directly and resets XP progress toward the next level.</small>
    <form className="admin-controls" onSubmit={e=>{e.preventDefault();if(enabled)apply('upgradeAdd',{upgrade});}}><label>Add upgrade<select value={upgrade} disabled={!enabled} onChange={e=>setUpgrade(e.target.value)}>{UPGRADES.map(u=><option key={u.id} value={u.id}>{u.name} · {u.rarity}</option>)}</select></label><button className="secondary" disabled={!enabled||!upgrade} type="submit">Add upgrade</button></form>
    <form className="admin-controls" onSubmit={e=>{e.preventDefault();if(enabled&&selectedRemoveUpgrade)apply('upgradeRemove',{upgrade:selectedRemoveUpgrade});}}><label>Remove owned upgrade<select value={selectedRemoveUpgrade} disabled={!enabled||!ownedUpgrades.length} onChange={e=>setRemoveUpgrade(e.target.value)}>{ownedUpgrades.length?ownedUpgrades.map((id,index)=><option key={`${id}-${index}`} value={id}>{UPGRADES.find(u=>u.id===id)?.name||id}{ownedUpgrades.slice(0,index).includes(id)?' · stack':''}</option>):<option value="">No upgrades owned</option>}</select></label><button className="secondary" disabled={!enabled||!ownedUpgrades.length} type="submit">Remove upgrade</button></form>
    <form className="admin-controls" onSubmit={e=>{e.preventDefault();if(enabled)apply('curseAdd',{curse,rarity});}}><label>Add curse<select value={curse} disabled={!enabled} onChange={e=>setCurse(e.target.value)}>{CURSES.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Curse rarity<select value={rarity} disabled={!enabled} onChange={e=>setRarity(e.target.value)}>{['common','rare','epic','legendary'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><button className="secondary" disabled={!enabled||!curse} type="submit">Add curse</button></form>
    <form className="admin-controls" onSubmit={e=>{e.preventDefault();if(enabled&&ownedCurses.length)apply('curseRemove',{index:Number(removeCurse)});}}><label>Remove curse<select value={ownedCurses.length?Math.min(Number(removeCurse),ownedCurses.length-1):''} disabled={!enabled||!ownedCurses.length} onChange={e=>setRemoveCurse(e.target.value)}>{ownedCurses.length?ownedCurses.map((c,index)=><option key={`${c.id}-${index}`} value={index}>{c.name} · {c.rarity||'common'}</option>):<option value="">No curses active</option>}</select></label><button className="secondary" disabled={!enabled||!ownedCurses.length} type="submit">Remove curse</button></form>{notice&&<p className="admin-notice" role="status">{notice}</p>}
  </section>;
}
