import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createGame,player,spawnEnemy,step} from '../game/engine.js';
import {ENEMIES,WEAPONS} from '../game/config.js';
const setup=(name='hacker',weapon='sword')=>{const p=player('p',name,weapon),g=createGame([p],42);g.enemies=[];g.obstacles=[];g.intro=0;p.x=200;p.y=200;p.invuln=0;return {g,p};};
test('hacker kills every enemy and boss with one landed melee hit using every weapon',()=>{for(const kind of Object.keys(ENEMIES))for(const weapon of Object.keys(WEAPONS)){const {g,p}=setup('hacker',weapon);g.stage=1;const e=spawnEnemy(g,kind,230,200);e.stun=10;e.hp=e.maxHp=1000000;step(g,{p:{attack:true,angle:0}},1/60);assert.equal(e.hp,0,`${weapon} / ${kind}`);assert.equal(p.kills,1);assert.equal(p.xp,1);}});
test('only the exact hacker username gets the Easter egg',()=>{for(const name of ['Adventurer','Hacker','hacker2',' hacker']){const {g,p}=setup(name),e=spawnEnemy(g,'boss',230,200);e.stun=10;step(g,{p:{attack:true,angle:0}},1/60);assert.equal(e.hp,e.maxHp-WEAPONS.sword.damage);assert.equal(p.kills,0);}});
test('hacker reflected projectiles also kill bosses in one hit, including zero-damage darts',()=>{for(const damage of [0,12]){const {g,p}=setup(),e=spawnEnemy(g,'boss',290,200);e.stun=10;g.bullets=[{x:220,y:200,vx:-350,vy:0,kind:damage?'pistol':'magnet',damage,life:4,owner:'',radius:4}];step(g,{p:{parry:1,angle:0}},1/60);assert.equal(g.bullets[0].owner,p.id);for(let i=0;i<12&&e.hp>0;i++)step(g,{},1/60);assert.equal(e.hp,0);assert.equal(p.kills,1);}});
test('co-op applies the damage override only to the projectile owner and survives JSON snapshots',()=>{for(const owner of ['p','ally']){const {g}=setup();g.players.push(player('ally','Adventurer'));const e=spawnEnemy(g,'boss',300,200);e.stun=10;g.bullets=[{x:280,y:200,vx:350,vy:0,damage:12,kind:'pistol',owner,life:4,radius:4}];const copy=JSON.parse(JSON.stringify(g));step(copy,{},1/60);assert.equal(copy.enemies.length,owner==='p'?0:1);if(owner==='ally')assert.equal(copy.enemies[0].hp,e.maxHp-12);}});
