import {test} from 'node:test';import assert from 'node:assert/strict';import{createGame,player,step}from'../game/engine.js';import{beginRoute,openRouteDoors,selectRoute}from'../game/run-content.js';
const setup=()=>{const g=createGame([player('h','Host'),player('g','Guest')],42);g.runSystems=true;g.hostId='h';g.scrap=120;g.players.forEach(p=>{p.x=450;p.y=285;});beginRoute(g);return g;};
const tick=(g,input)=>step(g,input,1/60);
test('ordinary routes open left combat and right altar doors while boss routes require the shop',()=>{const g=setup();assert.ok(g.routeOptions.includes('continue')&&g.routeOptions.includes('altar'));assert.equal(g.routeDoors.find(d=>d.choice==='continue').side,'left');assert.equal(g.routeDoors.find(d=>d.choice==='altar').side,'right');g.room=3;beginRoute(g);assert.deepEqual(g.routeOptions,['shop']);assert.equal(g.routeDoors[0].side,'bottom');});
test('host must walk outward through the physical opening; remote and guest route choices fail',()=>{const g=setup(),[host,guest]=g.players,d=g.routeDoors.find(d=>d.choice==='continue');assert.throws(()=>selectRoute(g,host.id,'continue'),/Walk through/);guest.x=60;guest.y=d.y;tick(g,{g:{mx:-1}});assert.equal(g.phase,'route');host.x=60;host.y=d.y;tick(g,{h:{mx:1}});assert.equal(g.phase,'route');tick(g,{h:{mx:-1}});assert.equal(g.phase,'combat');assert.equal(g.room,1);assert.equal(g.routeDoors.length,0);assert.equal(g.scrap,120);assert.throws(()=>selectRoute(g,guest.id,'altar'));});
test('altar and shop entrances preserve stats and keep the next combat room pending',()=>{for(const choice of ['altar','shop']){const g=setup();g.routeOptions=[choice];openRouteDoors(g);const p=g.players[0],d=g.routeDoors[0];p.hp=47;p.shieldDamage=70;p.upgrades=['edge'];p.x=d.side==='bottom'?d.x:g.width-60;p.y=d.side==='bottom'?g.height-60:d.y;tick(g,{h:d.side==='bottom'?{my:1}:{mx:1}});assert.equal(g.phase,choice);assert.equal(g.room,0);assert.equal(g.pendingRoom,1);assert.equal(p.hp,47);assert.equal(p.shieldDamage,70);assert.deepEqual(p.upgrades,['edge']);}});
test('cleared room keeps its scenery and unrelated cover, clears hazards, and opens unobstructed door corridors',()=>{const g=setup();g.obstacles=[{x:45,y:g.height*.64-20,w:70,h:45},{x:300,y:170,w:55,h:55}];g.hazards=[{kind:'beam',remaining:1}];g.bullets=[{life:4}];const seed=g.scenerySeed;beginRoute(g);assert.deepEqual(g.obstacles,[{x:300,y:170,w:55,h:55}]);assert.equal(g.scenerySeed,seed);assert.equal(g.hazards.length,0);assert.equal(g.bullets.length,0);});
test('a downed host revives for routing without receiving an extra transition heal',()=>{const g=setup(),[h]=g.players;h.hp=0;h.maxHp=120;beginRoute(g);assert.equal(h.hp,60);const d=g.routeDoors.find(d=>d.choice==='continue');h.x=60;h.y=d.y;tick(g,{h:{mx:-1}});assert.equal(g.phase,'combat');assert.equal(h.hp,60);assert.equal(h.routeRevived,false);});
test('a persisted route snapshot advances identically through the same physical door',()=>{const g=setup(),p=g.players[0],d=g.routeDoors.find(d=>d.choice==='altar');p.x=g.width-60;p.y=d.y;const copy=JSON.parse(JSON.stringify(g));tick(g,{h:{mx:1}});tick(copy,{h:{mx:1}});assert.equal(g.phase,'altar');assert.deepEqual(JSON.parse(JSON.stringify(g)),JSON.parse(JSON.stringify(copy)));});
