import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createGame,player,step,spawnEnemy,hitPlayer,chooseUpgrade,adminTeleport} from '../game/engine.js';
import {createRun,claimKit,KITS,beginRoute,selectRoute,openRouteDoors,buyItem,sacrifice,upgradeOffers,grantUpgrade} from '../game/run-content.js';
import {UPGRADES} from '../game/config.js';
import {member,roomState,applyAction,advanceRoom} from '../game/rooms.js';
const tick=(g,n=1,inputs={})=>{for(let i=0;i<n;i++)step(g,inputs,1/60);};
const draft=n=>createRun(Array.from({length:n},(_,i)=>player('p'+i,'Tester')),42);
const pickAll=g=>{const kits=[...g.kits];for(const [i,p] of g.players.entries()){p.x=kits[i].x;p.y=kits[i].y;claimKit(g,p.id,kits[i].id);}};
const takeRoute=(g,id,choice)=>{openRouteDoors(g);const p=g.players.find(p=>p.id===id),d=g.routeDoors.find(d=>d.choice===choice);p.x=d.x;p.y=d.y;selectRoute(g,id,choice);};
const stop=(kind='shop')=>{const g=draft(2);pickAll(g);g.room=1;beginRoute(g);g.routeOptions=['continue',kind];takeRoute(g,g.hostId,kind);g.scrap=300;for(const p of g.players){p.x=g.station.x;p.y=g.station.y;p.vendorOpen=kind==='shop';p.altarOpen=kind==='altar';}return g;};
test('physical draft has three solo pickups or players plus two, with exclusive first-claim ownership',()=>{for(const n of [1,2,3,4]){const g=draft(n);assert.equal(g.phase,'draft');assert.equal(g.enemies.length,0);assert.equal(g.kits.length,n===1?3:n+2);assert.equal(new Set(g.kits.map(k=>k.id)).size,g.kits.length);const first=g.kits[0],p=g.players[0];p.x=30;assert.throws(()=>claimKit(g,p.id,first.id));p.x=first.x;p.y=first.y;claimKit(g,p.id,first.id);const kit=KITS.find(k=>k.id===first.id);assert.equal(p.weapon,kit.weapon);for(const u of kit.upgrades)assert.ok(p.upgrades.includes(u));assert.throws(()=>claimKit(g,p.id,g.kits[1]?.id||first.id));if(n>1){const q=g.players[1];q.x=first.x;q.y=first.y;assert.throws(()=>claimKit(g,q.id,first.id));for(const q of g.players.slice(1)){const next=g.kits.find(k=>!k.claimedBy);q.x=next.x;q.y=next.y;claimKit(g,q.id,next.id);}}assert.equal(g.phase,'combat');assert.equal(g.kits.length,0);assert.ok(g.enemies.length);}});
test('E claims a nearby kit; moving in the draft cannot attack or buy a distant pickup',()=>{const g=draft(1),p=g.players[0],kit=g.kits[0];p.x=kit.x;p.y=kit.y;tick(g,1,{p0:{interact:1,attack:true}});assert.equal(g.phase,'combat');assert.equal(p.kitId,kit.id);});
test('qualified synergy offers appear often but are not guaranteed; unavailable synergies never appear',()=>{const g=createGame([player('p','Tester')],42),p=g.players[0];for(let i=0;i<100;i++)assert.ok(upgradeOffers(g,p).every(id=>!UPGRADES.find(u=>u.id===id).kind));grantUpgrade(p,'stun');grantUpgrade(p,'area');let count=0;for(let i=0;i<1000;i++)if(upgradeOffers(g,p).includes('stunNova'))count++;assert.ok(count>550&&count<750);grantUpgrade(p,'stunNova');assert.throws(()=>grantUpgrade(p,'stunNova'));for(let i=0;i<50;i++)assert.ok(!upgradeOffers(g,p).includes('stunNova'));});
test('Scrap belongs to the party, is awarded once per kill, and survives an individual death',()=>{const g=draft(2);pickAll(g);g.intro=0;g.enemies=[];g.obstacles=[];const p=g.players[0];p.name='hacker';p.x=200;p.y=200;p.angle=0;const e=spawnEnemy(g,'brawler',230,200);e.stun=100;tick(g,1,{p0:{attack:true}});assert.equal(e.hp,0);assert.equal(g.scrap,8);tick(g);assert.equal(g.scrap,8);p.hp=0;g.phase='combat';spawnEnemy(g,'bow',800,400);tick(g);assert.equal(g.scrap,8);g.players[1].hp=0;tick(g);assert.equal(g.phase,'death');assert.equal(g.scrap,0);});
test('extra stops retain combat room numbering and a vending stop is guaranteed before each boss',()=>{const g=draft(1);pickAll(g);for(const stage of [0,1]){g.stage=stage;g.room=3;beginRoute(g);assert.equal(g.pendingRoom,4);assert.deepEqual(g.routeOptions,['shop']);takeRoute(g,g.hostId,'shop');assert.equal(g.room,3);assert.equal(g.phase,'shop');const p=g.players[0];p.x=g.exit.x;p.y=g.exit.y;tick(g,1,{p0:{interact:p.seenInteract+1}});assert.equal(g.phase,'combat');assert.equal(g.room,4);assert.ok(g.enemies.some(e=>e.kind=== (stage===0?'boss':'twinBomber')));}});
test('vending requires interaction and proximity, consumes shared Scrap and cannot oversell stock',()=>{const g=stop(),[p,q]=g.players;g.scrap=45;p.vendorOpen=false;assert.throws(()=>buyItem(g,p.id,'repair'));p.vendorOpen=true;p.shieldDamage=100;p.shieldBroken=true;q.shieldDamage=80;buyItem(g,p.id,'repair');assert.equal(p.shieldDamage,0);assert.equal(p.shieldBroken,false);assert.equal(g.scrap,0);assert.throws(()=>buyItem(g,q.id,'repair'));g.scrap=300;const item=g.stock.find(s=>UPGRADES.some(u=>u.id===s.id&&!u.kind));buyItem(g,p.id,item.id);const before=g.scrap;assert.throws(()=>buyItem(g,q.id,item.id));assert.equal(g.scrap,before);p.x=130;assert.throws(()=>buyItem(g,p.id,'heal'));});
test('sacrifices are optional, individual, once per altar, and permanently scale future maximum-health gains',()=>{const g=stop('altar'),[p,q]=g.players;const old=p.maxHp,other=q.maxHp,id=g.altarOffers[0];sacrifice(g,p.id,id);assert.equal(p.maxHp,old-Math.ceil(old*.25));assert.equal(p.healthFactor,.75);assert.equal(q.maxHp,other);assert.ok(p.upgrades.includes(id));assert.throws(()=>sacrifice(g,p.id,g.altarOffers[1]));const max=p.maxHp;grantUpgrade(p,'vitality');assert.equal(p.maxHp,max+18);assert.equal(p.healthFactor,.75);adminTeleport(g,2,5);assert.equal(p.healthFactor,.75);assert.ok(p.upgrades.includes(id));});
test('new passive and relic effects change combat and never damage the immune bomber',()=>{const p=player('p','Tester'),g=createGame([p],42);g.enemies=[];g.obstacles=[];g.intro=0;p.x=200;p.y=200;p.invuln=0;const enemy=spawnEnemy(g,'brawler',260,200),immune=spawnEnemy(g,'suicide',240,200);for(const id of ['stun','area','stunNova','mirrorEngine','recovery'])grantUpgrade(p,id);p.hp=70;p.parryLeft=.2;p.parryAge=0;p.angle=0;assert.equal(hitPlayer(g,p,10,true,0),'perfect');assert.equal(p.hp,72);assert.ok(enemy.stun>=1.5);assert.equal(immune.stun,0);assert.equal(g.bullets.filter(b=>b.owner===p.id).length,3);grantUpgrade(p,'stormHeart');p.invuln=0;const hp=enemy.hp,bomberHp=immune.hp;tick(g,1,{p:{dash:1,mx:1,angle:0}});assert.ok(enemy.hp<hp);assert.equal(immune.hp,bomberHp);});
test('only the current host chooses routes, shared stock remains deterministic across snapshots',()=>{const host=member('Host','sword',0),guest=member('Guest','dagger',0),r=roomState(host,0);r.members.push(guest);r.game=stop();r.game.hostId=host.id;r.game.players[0].id=host.id;r.game.players[1].id=guest.id;r.game.phase='route';r.game.routeOptions=['shop'];assert.throws(()=>applyAction(r,guest,{action:'route',choice:'shop'},0),/host/);openRouteDoors(r.game);const d=r.game.routeDoors.find(d=>d.choice==='shop');r.game.players[0].x=d.x;r.game.players[0].y=d.y;applyAction(r,host,{action:'route',choice:'shop'},0);const copy=JSON.parse(JSON.stringify(r.game));tick(r.game,40);tick(copy,40);assert.deepEqual(JSON.parse(JSON.stringify(r.game)),copy);host.lastSeen=-20000;guest.lastSeen=100;advanceRoom(r,100);assert.equal(r.host,guest.id);assert.equal(r.game.hostId,guest.id);});
test('completing a room grants a normal upgrade then exposes an extra route instead of incrementing room early',()=>{const g=draft(1);pickAll(g);g.enemies=[];tick(g);assert.equal(g.phase,'upgrade');const p=g.players[0];assert.equal(chooseUpgrade(g,p.id,p.offers[0]),true);tick(g);assert.equal(g.phase,'route');assert.equal(g.room,0);assert.equal(g.pendingRoom,1);});
test('a drafted campaign preserves run traits through all ten combat rooms and both required boss shops',()=>{
 const g=draft(1);pickAll(g);const p=g.players[0];grantUpgrade(p,'edge');g.scrap=220;p.healthFactor=.75;p.maxHp=75;p.shieldDamage=60;
 let rooms=0,shops=0;
 for(let stage=0;stage<2;stage++)for(let room=0;room<5;room++){
  assert.equal(g.stage,stage);assert.equal(g.room,room);assert.equal(g.phase,'combat');rooms++;
  if(room===4)assert.deepEqual(g.enemies.filter(e=>['boss','twinBomber','twinRicochet'].includes(e.kind)).map(e=>e.kind),stage===0?['boss']:['twinBomber','twinRicochet']);
  g.enemies=[];g.hazards=[];g.bullets=[];tick(g);
  if(room<4){assert.equal(g.phase,'upgrade');assert.ok(chooseUpgrade(g,p.id,p.offers.find(id=>id!=='vitality')));tick(g);const choice=room===3?'shop':'continue';takeRoute(g,p.id,choice);if(choice==='shop'){shops++;assert.equal(g.room,3);p.x=g.exit.x;p.y=g.exit.y;tick(g,1,{p0:{interact:p.seenInteract+1}});}}
  else if(stage===0){assert.equal(g.phase,'levelclear');assert.equal(p.hp,p.maxHp);assert.equal(p.shieldDamage,60);tick(g,1,{p0:{interact:p.seenInteract+1}});assert.equal(p.shieldDamage,0);}
 }
 assert.equal(g.phase,'victory');assert.equal(rooms,10);assert.equal(shops,2);assert.equal(g.scrap,220);assert.equal(p.healthFactor,.75);assert.ok(p.upgrades.includes('edge'));assert.equal(p.hp,p.maxHp);
});
test('serialized combat retains deterministic trait effects and friendly mirror projectiles',()=>{
 const g=draft(1);pickAll(g);const p=g.players[0];for(const id of ['stun','area','stunNova','mirrorEngine','rebound','dashSpark','thunderStep','echoBlade'])grantUpgrade(p,id);g.intro=0;p.parryLeft=.2;p.parryAge=0;p.invuln=0;hitPlayer(g,p,10,true,p.angle);
 const copy=JSON.parse(JSON.stringify(g));for(let i=0;i<300;i++){const input={p0:{attack:true,guard:true,parry:i+1,dash:i+1,mx:Math.cos(i*.1),my:Math.sin(i*.1),angle:i*.05}};tick(g,1,input);tick(copy,1,input);}assert.deepEqual(JSON.parse(JSON.stringify(g)),JSON.parse(JSON.stringify(copy)));
});
